### PR TITLE
Add index.js to avoid flow module node found error.

### PR DESCRIPTION
**Pull request by shouze**
When I'm using facebook flow 
```
src/Common/Domain/AesEncryptionService.js:4
  4: var MCrypt = require('mcrypt').MCrypt;
                  ^^^^^^^^^^^^^^^^^ mcrypt. Required module not found


Found 1 error
```

capture d ecran 2016-01-25 a 11 52 01

### CODE REVIEW

**Comment by shouze** [comment]
thx @tugrul ;)

I wonder if
```js
module.exports = require('./build/Release/mcrypt');
```

wasn't more appropriate in the index.js file.

Also... I can't install this package with the merged patch even if I put something like that in package.js of my project:
```js
"mcrypt": "tugrul/node-mcrypt#master",
```

I've found why: npm don't do git submodule clone when I install from a non tagged release... probably a npm bug... I've found no way to fix that even trying to make a git submodule from package.json install step.

Would you please bump a new patch release, 0.1.10? I can make the PR if you want.

**Comment by shouze** [comment]
@tugrul in case, done in https://github.com/tugrul/node-mcrypt/pull/50 ;)

**Comment by tugrul** [comment]
Thank you. I'm going to publish a release to NPM

**Comment by shouze** [comment]
thank you @tugrul :+1:

**Pull request merged**
